GET http://localhost:8081/products HTTP/1.1

### DISPLAY FLUFFY: ###

GET http://localhost:8081/products/1 HTTP/1.1

### CREATE PRODUCT (NO AUTHHEADER): ###

POST http://localhost:8081/products HTTP/1.1
content-type: application/json

{
    "name": "Hamish",
    "price": 7.95
}

### CREATE PRODUCT (AUTHHEADER SUPPLIED): ###

POST http://localhost:8081/products HTTP/1.1
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiQm9iIiwicGFzc3dvcmRfaGFzaCI6IiQyYSQxMCRJaVFkNHk1Z2JPNEluZWRQRjJhck1lcGRWOElSQkhQeFgvTHBMc3U3YTh2NWM1N2NpdG0zYSJ9LCJpYXQiOjE2MTUyMDk0MzN9.8F_UqgE3S0ejsFma_5PuBtQX8EtZTlNrhug7CjMQJOI
content-type: application/json

{
    "name": "Hamish",
    "price": 7.95
}

### EDIT PRODUCT: ###
PUT http://localhost:8081/products/1 HTTP/1.1
content-type: application/json

{
    "name": "Nutmeg"
}

### DELETE product: ###

DELETE http://localhost:8081/products/3 HTTP/1.1