### AUTHHEADERS ###
### Authheaders must be manually supplied in these rest calls
### The authheader can be gleaned from running the auth in user.rest
### Remember to start the header with `Bearer: `
### Also remembrt headers should not be in quote marks


### CREATE THE FIRST USER ###
POST http://localhost:8081/api/v1/users/genesis HTTP/1.1
content-type: application/json

{
    "firstname": "Adam",
    "lastname": "The First",
    "password_clear": "inTheBeginning"
}


### DISPLAY ALL USERS: ###

GET http://localhost:8081/api/v1/users HTTP/1.1
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImZpcnN0bmFtZSI6IkJvYmJpbmd0b24iLCJwYXNzd29yZCI6IiQyYSQxMCRLOUZxcG95dVBZU2RaMmpOMFg3a2guS2M3djhBdmovdTlJakYydnJxMzl3RGZsa2RPTE1QMiJ9LCJpYXQiOjE2MTUyOTEzODR9.IyGadxDBHnWsg2Cnv_3-yGFQP1ICs2nLRRna5Tjnj3w

### CREATE A BOB: ###

POST http://localhost:8081/api/v1/users/ HTTP/1.1
content-type: application/json

{
    "firstname": "Bob",
    "lastname": "Bobbington",
    "password_clear": "bobsPassword"
}


### AUTHENTICATE WITH THE CORRECT PASSWORD: ###

GET http://localhost:8081/api/v1/users/authenticate HTTP/1.1
content-type: application/json

{
    "id": "1",
    "password_clear": "bobsPassword"
}

### AUTHENTICATE WITH THE WRONG PASSWORD: ###

GET http://localhost:8081/api/v1/users/authenticate HTTP/1.1
content-type: application/json

{
    "id": "1",
    "password_clear": "wrongPassword"
}


### DELETE A USER: ###
### ONLY FOR TESTING ###
DELETE http://localhost:8081/api/v1/users/ HTTP/1.1
content-type: application/json

{
    "id": 2
}